ikemo3/gossip-site-blocker

- apps/content_script/document_start/start.js
- apps/content_script/document_start/start.ts
Google Newsのブロックのリトライがされていなかったのを修正
> Fix: Retry Google News blocking is missing.

- apps/content_script/google_element.js
- apps/content_script/google_element.ts
> Not work due to changed Google search results

- PRIVACY.md
> add privacy policy.

- apps/common.js
- apps/common.ts
- apps/content_script/google_element.ts
- apps/option/banned_word.ts
* Fix `@ts-ignore` position.
* Remove useless type declaration.
* Change HTMLElement  -> HTMLDivElement
> fix: TypeScript error.

- .circleci/config.yml
- Makefile
- scripts/ci.sh
See below (Japanese)
https://qiita.com/sonatard/items/93ca46fdd51e4f17ad98
> ci: migrate .circleci/config.yml to Makefile

- .circleci/config.yml
- .gitignore
- package.json
- scripts/archive.sh
- scripts/ci.sh
- scripts/deploy.sh
* separate archive.sh from ci.sh
* change workspace to `tmp/workspace` from `/tmp/workspace`
> build: refactor archive script

- scripts/deploy.sh
* fix(deploy): incorrect current directory
* fix(deploy): release name is incorrect
* fix(deploy): exit code of jq is reversed
* refactor(build): use `[[`, `]]` instead of `[`, `]`
> build: fix deploy script

- scripts/archive.sh
* refactor(build): add/remove echos and comments
* build: set `version_name` for snapshot
> build: refactor archive.sh

- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
* TypeScript: Not indent 'case' branches
* TypeScript: Use single quotes in new code
> ide: update code style

- CHANGELOG.md
- apps/common.ts
> fix: featured snippets

- .gitignore
- .idea/inspectionProfiles/Project_Default.xml
- .idea/search-result-blocker.iml
- apps/content_script/google.css
- package.json
- test/selenium/test.ts
- tsconfig.json
- yarn.lock
> fix: block anchor is not shown in the Google Top News

- apps/content_script/google_inner_card.ts
> fix: cannot click the icon with compact mode(#41)

- apps/content_script/google.css
> fix: video url overflows in firefox(#88)

- .circleci/config.yml
- test/selenium/test.ts
* ci: change Firefox language to Japanese
* refactor(test): stop using tesseract
* refactor(test): extract constant
* test: fix wrong use driver
> test: refactor

- apps/content_script/document_start/start.ts
* refactor: extract type `IBlockFunction`
* refactor: remove duplicted function.
> refactor: start.ts

- apps/_locales/en/messages.json
- apps/_locales/ja/messages.json
- apps/content_script/block_target_factory.ts
> fix: urls by banned words does not show hard blocked

- apps/content_script/google.css
> fix: wrong menu position in compact mode

- apps/_locales/en/messages.json
- apps/_locales/ja/messages.json
- apps/entry/document_idle.ts
- apps/entry/options.ts
- apps/option/options.html
- apps/repository/config.ts
> Improvement: add option for display `Temporarily unblock all`

- apps/_locales/en/messages.json
- apps/_locales/ja/messages.json
- apps/block/google_news_tab_card_section.ts
- apps/block/google_news_tab_top.ts
- apps/entry/document_start.ts
- apps/entry/options.ts
- apps/option/options.html
- apps/repository/config.ts
- apps/styles/google.css
> Block 'News' tab individually

- apps/styles/google.css
> improve: smaller font size

- apps/model/recommend.ts
- test/recommend.test.ts
* improve: add Twitter for 'Block recommend path'(closes #57)
* improve: add atwiki for 'Block recommend path'(closes #29)
* improve: add wikiwiki for 'Block recommend path'(closes #175)
> improve: recommend

- apps/content_script/appbar.ts
- apps/entry/document_idle.ts
> fix: disable 'temporarily unblock all' causes disable 'show information of blocked by banned words'

- .eslintrc.json
- apps/entry/options-tabby.ts
- apps/entry/tabby.ts
- apps/option/options.html
- package.json
- webpack.config.ts
- yarn.lock
> use tabby for option

- apps/block/block.ts
- apps/block/google_news_tab_card_section.ts
- apps/block/google_news_tab_top.ts
- apps/block/google_search_inner_card.ts
- apps/block/google_search_result.ts
- apps/block/google_search_top_news.ts
* change SearchResultToBlock to abstract class
* add abstract methods
* `getTitle()`
* `getContents()`
* default implementations
* `contains(string)`
* `containsInTitle(string)`
* `deleteElement()`
> refactor: extract base class

- apps/block/google_news_tab_card_section.ts
- apps/block/google_news_tab_top.ts
- apps/block/google_search_result.ts
- apps/block/google_search_top_news.ts
> refactor: rename to compactMenuInsertElement

- apps/block/google_search_top_news.ts
- apps/entry/document_start.ts
Reverts ikemo3/gossip-site-blocker#202
> Revert "refactor: merge code blocks"

- apps/entry/document_start.ts
Reverts ikemo3/gossip-site-blocker#201
> Revert "refactor: integrate code blocks"

- apps/_locales/en/messages.json
- apps/_locales/ja/messages.json
- apps/block/block.ts
- apps/block/google_image_tab.ts
- apps/entry/document_start.ts
- apps/entry/options.ts
- apps/option/options.html
- apps/repository/config.ts
- apps/styles/google.css
- apps/values/document_url.ts
> feature: block images

- apps/content_script/block_state.ts
- test/block_state.test.ts
> fix: correct block priority

- .circleci/config.yml
- CHANGELOG.md
- apps/block/google_news_card.ts
- apps/block/google_search_top_news.ts
- apps/entry/document_start.ts
- apps/styles/google.css
- scripts/ci.sh
- test/selenium/driver.ts
- test/selenium/run_all.ts
* Disable integration-test for CI.
* Add `console` for integration-test
> feature: block Google News Tab(card layout)

- apps/content_script/block_state.ts
> fix: catch exception by invalid regexp

- apps/block/google_news_tab_top.ts
> fix: 'News' tab does not work.

- apps/block/google_search_top_news.ts
Reverts ikemo3/gossip-site-blocker#690
> Revert "fix: can't block Top News"

- apps/entry/popup.ts
- apps/values/document_url.ts
- test/document_url.test.ts
> fix: can't redirect when URL has fragment

- apps/block/google_search_movie.ts
> remove as XXXX of TypeScript (file: google_search_movie.ts)

- apps/content_script/dialog.ts
> remove as XXXX of TypeScript (file: fix-203-dialog.ts)

- apps/block/google_news_result.ts
> remove as XXXX of TypeScript (file: google_news_result.ts)

- apps/block/google_news_section_with_header.ts
Fix https://github.com/ikemo3/gossip-site-blocker/issues/203
> remove as XXXX of TypeScript (file: fix-203-google_news_section_with_header.ts) 

- apps/content_script/appbar.ts
> remove as XXXX of TypeScript (file: appbar.ts)

- apps/storage/blocked_sites.ts
> remove as XXXX of TypeScript (file: fix-203-blocked_sites.ts)

- apps/storage/banned_words.ts
> remove as XXXX of TypeScript (file: fix-203-banned_words.ts)

- apps/page/option/export.ts
> remove as XXXX of TypeScript (file: fix-203-export.ts)

- apps/page/option/import.ts
> remove as XXXX of TypeScript (file: fix-203-import.ts)

- apps/entry/options.ts
> remove as XXXX of TypeScript (file: fix-203-options.ts) 

- apps/page/option/regexp.ts
> remove as XXXX of TypeScript (file: fix-203-regexp.ts)

- apps/page/option/banned_word.ts
> remove as XXXX of TypeScript (file: fix-203-banned_word.ts)

- apps/entry/popup.ts
> remove as XXXX of TypeScript (file: fix-203-popup.ts)
